//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<html><body><left><table border=\'1\' cellpadding=\'0\' cellspacing=\'0\'> \r\n<tr> \r\n<td" +
            " align=\'left\' valign=\'middle\'>Reference</td> \r\n<td align=\'left\' valign=\'middle\'>" +
            "Exporter</td> \r\n<td align=\'left\' valign=\'middle\'>EPU</td> \r\n<td align=\'left\' val" +
            "ign=\'middle\'>Entry</td> \r\n<td align=\'left\' valign=\'middle\'>Date</td> \r\n<td align" +
            "=\'left\' valign=\'middle\'>MRN</td> \r\n<td align=\'left\' valign=\'middle\'>Vehicle</td>" +
            " \r\n<td align=\'left\' valign=\'middle\'>Pkgs</td> \r\n<td align=\'left\' valign=\'middle\'" +
            ">Gross</td> \r\n<td align=\'left\' valign=\'middle\'>Route</td> \r\n<tr> \r\n<tr> \r\n<td al" +
            "ign=\'left\' valign=\'middle\'>DE124315A</td> \r\n<td align=\'left\' valign=\'middle\'>EUR" +
            "OPRIDE LTD</td> \r\n<td align=\'left\' valign=\'middle\'>011</td> \r\n<td align=\'left\' v" +
            "align=\'middle\'>A02582W</td> \r\n<td align=\'left\' valign=\'middle\'>15/03/16 00:00:00" +
            "</td> \r\n<td align=\'left\' valign=\'middle\'>16GB03X57775707030</td> \r\n<td align=\'le" +
            "ft\' valign=\'middle\'>AB84GYR / AB62GIR</td> \r\n<td align=\'left\' valign=\'middle\'></" +
            "td> \r\n<td align=\'left\' valign=\'middle\'>3378.500</td> \r\n<td align=\'left\' valign=\'" +
            "middle\'>6</td> \r\n</tr> \r\n<tr> \r\n<td align=\'left\' valign=\'middle\'>DE124315B</td> " +
            "\r\n<td align=\'left\' valign=\'middle\'>EUROPRIDE LTD</td> \r\n<td align=\'left\' valign=" +
            "\'middle\'>011</td> \r\n<td align=\'left\' valign=\'middle\'>A02585F</td> \r\n<td align=\'l" +
            "eft\' valign=\'middle\'>15/03/16 00:00:00</td> \r\n<td align=\'left\' valign=\'middle\'>1" +
            "6GB03X57775961017</td> \r\n<td align=\'left\' valign=\'middle\'>AB84GYR / AB62GIR</td>" +
            " \r\n<td align=\'left\' valign=\'middle\'></td> \r\n<td align=\'left\' valign=\'middle\'>297" +
            "0.000</td> \r\n<td align=\'left\' valign=\'middle\'>6</td> \r\n</tr> \r\n<tr> \r\n<td align=" +
            "\'left\' valign=\'middle\'>DE124315C</td> \r\n<td align=\'left\' valign=\'middle\'>EUROPRI" +
            "DE LTD</td> \r\n<td align=\'left\' valign=\'middle\'>011</td> \r\n<td align=\'left\' valig" +
            "n=\'middle\'>A02587V</td> \r\n<td align=\'left\' valign=\'middle\'>15/03/16 00:00:00</td" +
            "> \r\n<td align=\'left\' valign=\'middle\'>16GB03X57776136010</td> \r\n<td align=\'left\' " +
            "valign=\'middle\'>AB84GYR / AB62GIR</td> \r\n<td align=\'left\' valign=\'middle\'></td> " +
            "\r\n<td align=\'left\' valign=\'middle\'>5080.250</td> \r\n<td align=\'left\' valign=\'midd" +
            "le\'>6</td> \r\n</tr> \r\n<tr> \r\n<td align=\'left\' valign=\'middle\'>DE124315D</td> \r\n<t" +
            "d align=\'left\' valign=\'middle\'>EUROPRIDE LTD</td> \r\n<td align=\'left\' valign=\'mid" +
            "dle\'>011</td> \r\n<td align=\'left\' valign=\'middle\'>A02590B</td> \r\n<td align=\'left\'" +
            " valign=\'middle\'>15/03/16 00:00:00</td> \r\n<td align=\'left\' valign=\'middle\'>16GB0" +
            "3X57776358011</td> \r\n<td align=\'left\' valign=\'middle\'>AB84GYR / AB62GIR</td> \r\n<" +
            "td align=\'left\' valign=\'middle\'></td> \r\n<td align=\'left\' valign=\'middle\'>3415.00" +
            "0</td> \r\n<td align=\'left\' valign=\'middle\'>6</td> \r\n</tr> \r\n<tr> \r\n<td align=\'lef" +
            "t\' valign=\'middle\'>DE124315E</td> \r\n<td align=\'left\' valign=\'middle\'>OLD DOVER T" +
            "EXTILES LTD</td> \r\n<td align=\'left\' valign=\'middle\'>011</td> \r\n<td align=\'left\' " +
            "valign=\'middle\'>A02593J</td> \r\n<td align=\'left\' valign=\'middle\'>15/03/16 00:00:0" +
            "0</td> \r\n<td align=\'left\' valign=\'middle\'>16GB03X57776630011</td> \r\n<td align=\'l" +
            "eft\' valign=\'middle\'>AB84GYR / AB62GIR</td> \r\n<td align=\'left\' valign=\'middle\'><" +
            "/td> \r\n<td align=\'left\' valign=\'middle\'>1241.500</td> \r\n<td align=\'left\' valign=" +
            "\'middle\'>6</td> \r\n</tr> \r\n</table></left></body></html> \r\n")]
        public string DemoHtmlMessage {
            get {
                return ((string)(this["DemoHtmlMessage"]));
            }
            set {
                this["DemoHtmlMessage"] = value;
            }
        }
    }
}
